services:
  localdb:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=exemplelocalUser
      - POSTGRES_PASSWORD=exampleLocalUserPassowrd
      - POSTGRES_DB=LocalUserDb

  testdb:
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=exampleTestUser
      - POSTGRES_PASSWORD=exampleTestUserPassowrd
      - POSTGRES_DB=testUserDb