services:
  localdb:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=exampleDev
      - POSTGRES_PASSWORD=exampleDev
      - POSTGRES_DB=exampleDev
  testdb:
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=exampleTest
      - POSTGRES_PASSWORD=examleTest
      - POSTGRES_DB=exampleTest